import subprocess
import sys
import tempfile
import re
import json
import os
from pathlib import Path
from unittest import TestCase


ROOT = Path(__file__).resolve().parents[1]
CLI = ROOT / "scripts" / "repo_analyzer.py"
sys.path.insert(0, str(ROOT / "scripts"))
import repo_analyzer  # noqa: E402


def install_fake_repomix(bin_dir: Path) -> Path:
    fake = bin_dir / "npx"
    fake.write_text(
        """#!/usr/bin/env python3
import json
import sys
from pathlib import Path

args = sys.argv[1:]
log = Path(__file__).with_name("repomix-calls.jsonl")
with log.open("a", encoding="utf-8") as handle:
    handle.write(json.dumps(args, ensure_ascii=False) + "\\n")

try:
    output = Path(args[args.index("--output") + 1])
except (ValueError, IndexError):
    sys.exit("missing --output")
try:
    include = args[args.index("--include") + 1]
except (ValueError, IndexError):
    include = ""

output.parent.mkdir(parents=True, exist_ok=True)
output.write_text(
    "This file is a merged representation of a subset of the codebase, generated by fake repomix.\\n"
    "<repository_files>\\n"
    f"<file path=\\"fake-repomix.txt\\">include={include}</file>\\n"
    "</repository_files>\\n",
    encoding="utf-8",
)
""",
        encoding="utf-8",
    )
    fake.chmod(0o755)
    return fake


def install_fake_agent(bin_dir: Path) -> Path:
    fake = bin_dir / "fake-agent"
    fake.write_text(
        """#!/usr/bin/env python3
import sys
from pathlib import Path

prompt = sys.stdin.read()
log = Path(__file__).with_name("agent-prompts.log")
with log.open("a", encoding="utf-8") as handle:
    handle.write("---PROMPT---\\n")
    handle.write(prompt)
    handle.write("\\n")

if "覆盖率修复" in prompt:
    missing = ""
    for line in prompt.splitlines():
        if line.startswith("- 缺失符号:"):
            missing = line.split(":", 1)[1].strip()
    print("## Agent 覆盖率修复\\n\\n- 已补齐缺失符号: " + missing)
elif "Cross-ref 修复" in prompt:
    print("## Agent Cross-ref 修复\\n\\n- 已按独立审稿意见补齐模块边界说明。")
elif "独立审稿 agent" in prompt:
    print("## Agent Cross-ref 审稿\\n\\n- 未发现跨模块矛盾。\\n- 抽查范围: 05-module-ids.yaml, drafts/*.md, 08-coverage.md")
else:
    module_ids = []
    for line in prompt.splitlines():
        if line.startswith("### MODULE "):
            module_ids.append(line.split()[-1])
    if not module_ids:
        module_ids = ["module_001"]
    for module_id in module_ids:
        print(f"<!-- MODULE_RESULT: {module_id} -->")
        print("## Agent 深度分析\\n\\n- 业务角色: 该模块承载主要执行路径。\\n- 设计思路: 基于 repomix 切片和模块底稿判断。\\n- 证据: drafts/06-module-module_001.md")
        print("<!-- END_MODULE_RESULT -->")
""",
        encoding="utf-8",
    )
    fake.chmod(0o755)
    return fake


def install_fake_codex(bin_dir: Path) -> Path:
    fake = bin_dir / "codex"
    fake.write_text(
        """#!/usr/bin/env python3
import json
import os
import sys
from pathlib import Path

args = sys.argv[1:]
prompt = sys.stdin.read()
if "-C" in args:
    os.chdir(args[args.index("-C") + 1])
cwd = os.getcwd()
last_message = None
if "--output-last-message" in args:
    last_message = Path(args[args.index("--output-last-message") + 1])

log = Path(__file__).with_name("codex-calls.jsonl")
with log.open("a", encoding="utf-8") as handle:
    handle.write(json.dumps({"args": args, "cwd": cwd, "prompt": prompt}, ensure_ascii=False) + "\\n")

if "覆盖率修复" in prompt:
    output = "## Agent 覆盖率修复\\n\\n- 已补齐缺失符号: run"
elif "Cross-ref 修复" in prompt:
    output = "## Agent Cross-ref 修复\\n\\n- 已按独立审稿意见补齐模块边界说明。"
elif "独立审稿 agent" in prompt:
    output = "## Agent Cross-ref 审稿\\n\\n- 未发现跨模块矛盾。"
else:
    module_ids = []
    for line in prompt.splitlines():
        if line.startswith("### MODULE "):
            module_ids.append(line.split()[-1])
    if not module_ids:
        module_ids = ["module_001"]
    output = "\\n".join(
        f"<!-- MODULE_RESULT: {module_id} -->\\n## Agent 深度分析\\n\\n- 业务角色: 该模块承载主要执行路径。\\n- 证据: drafts/06-module-module_001.md\\n<!-- END_MODULE_RESULT -->"
        for module_id in module_ids
    )

if last_message:
    last_message.parent.mkdir(parents=True, exist_ok=True)
    last_message.write_text(output + "\\n", encoding="utf-8")
print(output)
""",
        encoding="utf-8",
    )
    fake.chmod(0o755)
    return fake


def install_fake_tree_sitter(bin_dir: Path) -> Path:
    fake = bin_dir / "tree-sitter"
    fake.write_text(
        """#!/usr/bin/env python3
import sys
from pathlib import Path

args = sys.argv[1:]
if args == ["--version"]:
    print("tree-sitter 0.99.0-fake")
elif args and args[0] == "parse":
    sys.exit(0)
elif args and args[0] == "query":
    source = Path(args[-1])
    text = source.read_text(encoding="utf-8")
    for name in ("run", "hidden_helper"):
        offset = text.find(name)
        if offset < 0:
            continue
        row = text[:offset].count("\\n")
        line_start = text.rfind("\\n", 0, offset) + 1
        column = offset - line_start
        print(f"pattern: 0, capture: name, start: ({row}, {column}), end: ({row}, {column + len(name)})")
else:
    sys.exit(1)
""",
        encoding="utf-8",
    )
    fake.chmod(0o755)
    return fake


class RepoAnalyzerCliTest(TestCase):
    def setUp(self):
        self._old_path = os.environ.get("PATH", "")
        self._fake_tools_tmp = tempfile.TemporaryDirectory()
        self.fake_tools = Path(self._fake_tools_tmp.name)
        install_fake_repomix(self.fake_tools)
        install_fake_agent(self.fake_tools)
        install_fake_codex(self.fake_tools)
        os.environ["PATH"] = f"{self.fake_tools}{os.pathsep}{self._old_path}"

    def tearDown(self):
        os.environ["PATH"] = self._old_path
        self._fake_tools_tmp.cleanup()

    def fake_repomix_calls(self):
        log = self.fake_tools / "repomix-calls.jsonl"
        if not log.exists():
            return []
        return [json.loads(line) for line in log.read_text(encoding="utf-8").splitlines()]

    def fake_codex_calls(self):
        log = self.fake_tools / "codex-calls.jsonl"
        if not log.exists():
            return []
        return [json.loads(line) for line in log.read_text(encoding="utf-8").splitlines()]

    def test_analyzes_local_repo_and_writes_core_artifacts(self):
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text("# Demo Tool\n\nA tiny command line tool.\n", encoding="utf-8")
            (repo / "pyproject.toml").write_text(
                '[project]\nname = "demo-tool"\nversion = "0.1.0"\n',
                encoding="utf-8",
            )
            (repo / "main.py").write_text(
                "def run():\n    return 'ok'\n\n\ndef search_docs(query):\n    return query\n",
                encoding="utf-8",
            )
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(
                ["git", "commit", "-m", "initial"],
                cwd=repo,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            result = subprocess.run(
                [sys.executable, str(CLI), str(repo), "--output", str(output), "--no-question"],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertTrue((output / "00-meta.txt").exists())
            self.assertTrue((output / "02a-repo-type.yaml").exists())
            self.assertTrue((output / "02a-manifest-card.md").exists())
            self.assertTrue((output / "slices" / "04-docs.xml").exists())
            docs_slice = (output / "slices" / "04-docs.xml").read_text(encoding="utf-8")
            self.assertIn("generated by fake repomix", docs_slice)
            calls = self.fake_repomix_calls()
            self.assertTrue(calls)
            self.assertTrue(all(call[:3] == ["--yes", "repomix", "."] for call in calls))
            self.assertTrue(all("--style" in call and call[call.index("--style") + 1] == "xml" for call in calls))
            self.assertTrue(all("--include" in call for call in calls))
            self.assertTrue((output / "ANALYSIS_REPORT.md").exists())
            self.assertTrue((output / "README.md").exists())
            self.assertIn("single-lang-CLI", (output / "02a-repo-type.yaml").read_text(encoding="utf-8"))
            report = (output / "ANALYSIS_REPORT.md").read_text(encoding="utf-8")
            self.assertIn("Demo Tool", report)
            self.assertIn("A tiny command line tool.", report)
            self.assertIn("python main.py", report)
            self.assertIn("name = \"demo-tool\"", report)
            self.assertIn("search_docs", report)
            self.assertTrue((output / "drafts" / "06-module-module_001.md").exists())

    def test_mode_all_writes_three_reports_and_acceptance_entrypoint(self):
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text("# Demo Tool\n", encoding="utf-8")
            (repo / "package.json").write_text(
                '{"name":"demo-tool","scripts":{"start":"node mcp_server_node.js"}}',
                encoding="utf-8",
            )
            (repo / "mcp_server_node.js").write_text(
                "const AI_TOOLS = [{ name: 'ai_search_web', description: 'Web search' }];\n"
                "async function main() { return AI_TOOLS; }\n",
                encoding="utf-8",
            )
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(
                ["git", "commit", "-m", "initial"],
                cwd=repo,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            result = subprocess.run(
                [sys.executable, str(CLI), str(repo), "--output", str(output), "--mode", "all", "--no-question"],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertTrue((output / "ANALYSIS_REPORT.tech-lead.md").exists())
            self.assertTrue((output / "ANALYSIS_REPORT.business.md").exists())
            self.assertTrue((output / "ANALYSIS_REPORT.learning.md").exists())
            self.assertTrue((output / "REPORT_DATA.json").exists())
            main_path = output / "ANALYSIS_REPORT.md"
            main = main_path.read_text(encoding="utf-8")
            tech = (output / "ANALYSIS_REPORT.tech-lead.md").read_text(encoding="utf-8")
            business = (output / "ANALYSIS_REPORT.business.md").read_text(encoding="utf-8")
            learning = (output / "ANALYSIS_REPORT.learning.md").read_text(encoding="utf-8")
            report_data = json.loads((output / "REPORT_DATA.json").read_text(encoding="utf-8"))
            self.assertEqual(report_data["project_name"], "demo-tool")
            self.assertIn("tech-lead", report_data["audiences"])
            self.assertIn("分析总览", main)
            self.assertIn("ANALYSIS_REPORT.tech-lead.md", main)
            self.assertNotEqual(main, tech)
            self.assertIn("技术负责人关注", tech)
            self.assertIn("业务负责人关注", business)
            self.assertIn("学习路径", learning)
            self.assertNotEqual(tech, business)
            self.assertNotEqual(tech, learning)
            check = output / "acceptance" / "check.sh"
            self.assertTrue(check.exists())
            self.assertTrue(check.read_text(encoding="utf-8").startswith("#!/bin/sh"))
            acceptance = subprocess.run([str(check)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertEqual(acceptance.returncode, 0, acceptance.stdout + acceptance.stderr)
            main_path.write_text(tech, encoding="utf-8")
            broken_main = subprocess.run([str(check)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertNotEqual(broken_main.returncode, 0, broken_main.stdout + broken_main.stderr)
            main_path.write_text(main, encoding="utf-8")
            (output / "ANALYSIS_REPORT.business.md").write_text(tech, encoding="utf-8")
            broken_audience = subprocess.run([str(check)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertNotEqual(broken_audience.returncode, 0, broken_audience.stdout + broken_audience.stderr)
            rerender = subprocess.run(
                [sys.executable, str(ROOT / "scripts" / "render_report.py"), "--template", "all", "--data", str(output)],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            self.assertEqual(rerender.returncode, 0, rerender.stderr)
            rerendered_acceptance = subprocess.run([str(check)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertEqual(rerendered_acceptance.returncode, 0, rerendered_acceptance.stdout + rerendered_acceptance.stderr)

    def test_acceptance_fails_when_report_drops_mcp_tool(self):
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text("# Search MCP\n", encoding="utf-8")
            (repo / "package.json").write_text('{"name":"search-mcp"}', encoding="utf-8")
            (repo / "mcp_server_node.js").write_text(
                "const AI_TOOLS = [{ name: 'ai_search_web', description: 'Web search' }];\n",
                encoding="utf-8",
            )
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(
                ["git", "commit", "-m", "initial"],
                cwd=repo,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            result = subprocess.run(
                [sys.executable, str(CLI), str(repo), "--output", str(output), "--mode", "all", "--no-question"],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            check = output / "acceptance" / "check.sh"
            passing = subprocess.run([str(check)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertEqual(passing.returncode, 0, passing.stdout + passing.stderr)
            report = output / "ANALYSIS_REPORT.md"
            report.write_text(report.read_text(encoding="utf-8").replace("ai_search_web", "removed_tool"), encoding="utf-8")
            broken_api = subprocess.run([str(check)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertNotEqual(broken_api.returncode, 0, broken_api.stdout + broken_api.stderr)

    def test_coverage_and_state_are_final_deterministic_outputs(self):
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text("# Demo Tool\n", encoding="utf-8")
            (repo / "main.py").write_text("def run():\n    return 'ok'\n", encoding="utf-8")
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(
                ["git", "commit", "-m", "initial"],
                cwd=repo,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            result = subprocess.run(
                [sys.executable, str(CLI), str(repo), "--output", str(output), "--no-question"],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            coverage = (output / "08-coverage.md").read_text(encoding="utf-8")
            state = (output / "STATE_REPORT.md").read_text(encoding="utf-8")
            self.assertNotIn("待 LLM 深度分析补全", coverage)
            self.assertNotIn("PASS_WITH_DETERMINISTIC_BASELINE", state)
            self.assertNotIn("§9 未完成模块明细", (output / "ANALYSIS_REPORT.md").read_text(encoding="utf-8"))

    def test_failed_modules_render_section_nine_and_schema(self):
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text("# Demo Tool\n", encoding="utf-8")
            (repo / "main.py").write_text("def run():\n    return 'ok'\n\ndef missing_api():\n    return 'x'\n", encoding="utf-8")
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

            result = subprocess.run(
                [
                    sys.executable,
                    str(CLI),
                    str(repo),
                    "--output",
                    str(output),
                    "--no-question",
                    "--target-coverage-core",
                    "1.01",
                ],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            state = (output / "STATE_REPORT.md").read_text(encoding="utf-8")
            report = (output / "ANALYSIS_REPORT.md").read_text(encoding="utf-8")
            self.assertIn("failed_modules:", state)
            self.assertIn("last_error: COVERAGE_FAILED", state)
            self.assertIn("coverage_ratio:", state)
            self.assertIn("suggested_recovery:", state)
            self.assertIn("## §9 未完成模块明细", report)
            self.assertIn("COVERAGE_FAILED", report)
            acceptance = subprocess.run([str(output / "acceptance" / "check.sh")], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertNotEqual(acceptance.returncode, 0, acceptance.stdout + acceptance.stderr)
            self.assertIn("FAIL|failed_modules tracked", acceptance.stdout)

    def test_report_only_links_existing_artifacts_and_history_ignores_dependencies(self):
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text("# Demo Tool\n", encoding="utf-8")
            (repo / "main.py").write_text("def run():\n    return 'ok'\n", encoding="utf-8")
            (repo / "node_modules").mkdir()
            (repo / "node_modules" / "ignored.js").write_text("console.log('noise')\n", encoding="utf-8")
            (repo / "uat-evidence").mkdir()
            (repo / "uat-evidence" / "old.md").write_text("待 LLM 深度分析补全\n", encoding="utf-8")
            (repo / "analysis").mkdir()
            (repo / "analysis" / "old.py").write_text("def stale_symbol():\n    pass\n", encoding="utf-8")
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(
                ["git", "commit", "-m", "initial"],
                cwd=repo,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            result = subprocess.run(
                [sys.executable, str(CLI), str(repo), "--output", str(output), "--no-question"],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            report = (output / "ANALYSIS_REPORT.md").read_text(encoding="utf-8")
            slice_refs = set(re.findall(r"slices/[A-Za-z0-9_.-]+", report))
            self.assertTrue(slice_refs)
            for ref in slice_refs:
                self.assertTrue((output / ref).exists(), ref)
            history = (output / "slices" / "12-history-hotspot.txt").read_text(encoding="utf-8")
            self.assertNotIn("node_modules", history)
            self.assertNotIn("uat-evidence", report)
            self.assertNotIn("stale_symbol", report)

    def test_reports_mcp_tool_names_from_source(self):
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text("# Search MCP\n", encoding="utf-8")
            (repo / "package.json").write_text(
                '{"name":"search-mcp","main":"mcp_server_node.js","dependencies":{"@modelcontextprotocol/sdk":"1.0.0"}}',
                encoding="utf-8",
            )
            (repo / "mcp_server_node.js").write_text(
                "const AI_TOOLS = [{ name: 'ai_search_web', description: 'Web search' },"
                "{ name: 'ai_search_github', description: 'GitHub search' }];\n",
                encoding="utf-8",
            )
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(
                ["git", "commit", "-m", "initial"],
                cwd=repo,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            result = subprocess.run(
                [sys.executable, str(CLI), str(repo), "--output", str(output), "--no-question"],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            report = (output / "ANALYSIS_REPORT.md").read_text(encoding="utf-8")
            self.assertIn("ai_search_web", report)
            self.assertIn("ai_search_github", report)

    def test_external_markdown_syntax_does_not_break_acceptance(self):
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text(
                "# Demo Tool\n\n"
                "See [Install](#install) and [[not_a_module]].\n\n"
                "```bash\n"
                "if [[ -z \"$DEST\" ]]; then\n"
                "  echo missing\n"
                "fi\n"
                "```\n",
                encoding="utf-8",
            )
            (repo / "main.py").write_text("def run():\n    return 'ok'\n", encoding="utf-8")
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(
                ["git", "commit", "-m", "initial"],
                cwd=repo,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            result = subprocess.run(
                [sys.executable, str(CLI), str(repo), "--output", str(output), "--mode", "all", "--no-question"],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            report = (output / "ANALYSIS_REPORT.md").read_text(encoding="utf-8")
            self.assertEqual(report.count("```") % 2, 0)
            acceptance = subprocess.run([str(output / "acceptance" / "check.sh")], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertEqual(acceptance.returncode, 0, acceptance.stdout + acceptance.stderr)

    def test_quality_gates_write_cross_ref_and_symbol_coverage(self):
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text("# Demo Tool\n", encoding="utf-8")
            (repo / "main.py").write_text(
                "def run():\n    return 'ok'\n\n"
                "def search_docs(query):\n    return query\n",
                encoding="utf-8",
            )
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

            result = subprocess.run(
                [sys.executable, str(CLI), str(repo), "--output", str(output), "--no-question"],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            draft = (output / "drafts" / "06-module-module_001.md").read_text(encoding="utf-8")
            self.assertIn("## 深度分析", draft)
            self.assertIn("## 关键路径", draft)
            self.assertIn("## 风险与缺口", draft)
            self.assertIn("## 证据", draft)
            self.assertIn("search_docs", draft)
            cross_ref = (output / "drafts" / "07-cross-ref-checks.md").read_text(encoding="utf-8")
            self.assertIn("PASS", cross_ref)
            coverage_json = json.loads((output / "coverage-symbols.json").read_text(encoding="utf-8"))
            self.assertIn("module_001", coverage_json["modules"])
            self.assertEqual(coverage_json["modules"]["module_001"]["status"], "PASS")
            self.assertIn(coverage_json["engine"]["engine"], {"regex-fallback", "tree-sitter+regex"})
            expected_json = json.loads((output / "expected-symbols.json").read_text(encoding="utf-8"))
            self.assertEqual(expected_json["engine"], coverage_json["engine"])
            self.assertTrue(any(item["name"] == "search_docs" for item in expected_json["symbols"]))
            coverage = (output / "08-coverage.md").read_text(encoding="utf-8")
            self.assertIn("engine:", coverage)
            self.assertIn("tree_sitter_available:", coverage)

            check = output / "acceptance" / "check.sh"
            passing = subprocess.run([str(check)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertEqual(passing.returncode, 0, passing.stdout + passing.stderr)

            (output / "expected-symbols.json").unlink()
            broken_expected = subprocess.run([str(check)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertNotEqual(broken_expected.returncode, 0, broken_expected.stdout + broken_expected.stderr)
            self.assertIn("required:expected-symbols.json", broken_expected.stdout)
            (output / "expected-symbols.json").write_text(json.dumps(expected_json), encoding="utf-8")

            draft_path = output / "drafts" / "06-module-module_001.md"
            draft_path.write_text(draft.replace("search_docs", "removed_symbol"), encoding="utf-8")
            broken = subprocess.run([str(check)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertNotEqual(broken.returncode, 0, broken.stdout + broken.stderr)
            self.assertIn("coverage symbol:module_001:search_docs", broken.stdout)

    def test_tree_sitter_query_engine_extracts_expected_symbols(self):
        install_fake_tree_sitter(self.fake_tools)
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text("# Demo Tool\n", encoding="utf-8")
            (repo / "main.py").write_text(
                "def run():\n"
                "    return 'ok'\n"
                "# hidden_helper is query-only in this test\n",
                encoding="utf-8",
            )
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

            result = subprocess.run(
                [sys.executable, str(CLI), str(repo), "--output", str(output), "--no-question"],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            expected = json.loads((output / "expected-symbols.json").read_text(encoding="utf-8"))
            self.assertEqual(expected["engine"]["engine"], "tree-sitter-query")
            self.assertEqual(expected["engine"]["queried_files"], 1)
            self.assertEqual(expected["engine"]["query_symbols"], 2)
            names = {item["name"] for item in expected["symbols"]}
            self.assertIn("hidden_helper", names)
            coverage = (output / "08-coverage.md").read_text(encoding="utf-8")
            self.assertIn("tree_sitter_queried_files: 1", coverage)
            self.assertIn("tree_sitter_query_symbols: 2", coverage)

    def test_agent_mode_runs_module_analysis_and_independent_review(self):
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text("# Demo Tool\n", encoding="utf-8")
            (repo / "main.py").write_text("def run():\n    return 'ok'\n", encoding="utf-8")
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

            result = subprocess.run(
                [
                    sys.executable,
                    str(CLI),
                    str(repo),
                    "--output",
                    str(output),
                    "--no-question",
                    "--agent-mode",
                    "command",
                    "--agent-command",
                    "fake-agent",
                    "--agent-max-attempts",
                    "2",
                ],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            summary = json.loads((output / "AGENT_SUMMARY.json").read_text(encoding="utf-8"))
            self.assertEqual(summary["mode"], "command")
            self.assertEqual(summary["status"], "PASS")
            self.assertEqual(summary["cross_ref"]["status"], "PASS")
            draft = (output / "drafts" / "06-module-module_001.md").read_text(encoding="utf-8")
            self.assertIn("## Agent 深度分析", draft)
            self.assertIn("agent-runs/modules-batch/result.md", draft)
            review = (output / "drafts" / "07-cross-ref-agent-review.md").read_text(encoding="utf-8")
            self.assertIn("## Agent Cross-ref 审稿", review)
            self.assertTrue((output / "agent-runs" / "modules-batch" / "prompt.md").exists())
            self.assertTrue((output / "agent-runs" / "cross-ref-review" / "attempt-1" / "metadata.json").exists())
            acceptance = subprocess.run([str(output / "acceptance" / "check.sh")], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertEqual(acceptance.returncode, 0, acceptance.stdout + acceptance.stderr)

    def test_codex_agent_runs_inside_analysis_dir_without_default_timeout(self):
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text("# Demo Tool\n", encoding="utf-8")
            (repo / "main.py").write_text("def run():\n    return 'ok'\n", encoding="utf-8")
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

            result = subprocess.run(
                [
                    sys.executable,
                    str(CLI),
                    str(repo),
                    "--output",
                    str(output),
                    "--no-question",
                    "--agent-mode",
                    "codex",
                    "--agent-max-attempts",
                    "1",
                ],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            calls = self.fake_codex_calls()
            self.assertTrue(calls)
            for call in calls:
                self.assertEqual(Path(call["cwd"]).resolve(), output.resolve())
                self.assertIn("-C", call["args"])
                self.assertEqual(Path(call["args"][call["args"].index("-C") + 1]).resolve(), output.resolve())
                self.assertIn("--sandbox", call["args"])
                self.assertEqual(call["args"][call["args"].index("--sandbox") + 1], "read-only")
                self.assertIn("--skip-git-repo-check", call["args"])
                self.assertIn('model_reasoning_effort="low"', call["args"])
                self.assertIn("不要调用任何 skill", call["prompt"])
                self.assertIn("不要写入任何文件", call["prompt"])
            metadata = json.loads((output / "agent-runs" / "modules-batch" / "attempt-1" / "metadata.json").read_text(encoding="utf-8"))
            self.assertIsNone(metadata["timeout_seconds"])
            self.assertEqual(metadata["timeout_config_seconds"], 0)
            self.assertEqual(metadata["command_kind"], "codex exec")
            self.assertEqual(Path(metadata["cwd"]).resolve(), output.resolve())
            effective = json.loads((output / "CONFIG_EFFECTIVE.json").read_text(encoding="utf-8"))
            self.assertEqual(effective["agent_timeout_seconds"], 0)
            sla = (output / "SLA_REPORT.md").read_text(encoding="utf-8")
            self.assertIn("agent_timeout: disabled", sla)
            performance_report = (output / "PERFORMANCE_REPORT.md").read_text(encoding="utf-8")
            self.assertIn("慢因结论", performance_report)
            self.assertIn("agent_timeout: disabled", performance_report)
            self.assertIn("modules-batch", performance_report)
            self.assertIn("不能把限时当成根因修复", performance_report)
            performance = json.loads((output / "PERFORMANCE_REPORT.json").read_text(encoding="utf-8"))
            self.assertEqual(performance["summary"]["agent_attempt_count"], len(calls))
            self.assertEqual(performance["summary"]["slowest_agent_run_id"], "modules-batch")
            self.assertTrue(any(item["name"] == "agent-modules-batch" for item in performance["stages"]))
            self.assertTrue(all(item["command_kind"] == "codex exec" for item in performance["agent_attempts"]))
            acceptance = subprocess.run([str(output / "acceptance" / "check.sh")], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertEqual(acceptance.returncode, 0, acceptance.stdout + acceptance.stderr)

    def test_agent_repair_loop_rewrites_failed_coverage_module(self):
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text("# Demo Tool\n", encoding="utf-8")
            functions = "\n\n".join(f"def api_{index:03d}():\n    return {index}" for index in range(405))
            (repo / "main.py").write_text(functions + "\n", encoding="utf-8")
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

            result = subprocess.run(
                [
                    sys.executable,
                    str(CLI),
                    str(repo),
                    "--output",
                    str(output),
                    "--no-question",
                    "--agent-mode",
                    "command",
                    "--agent-command",
                    "fake-agent",
                    "--target-coverage-core",
                    "1.0",
                ],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            summary = json.loads((output / "AGENT_SUMMARY.json").read_text(encoding="utf-8"))
            self.assertIn("module_001", summary["repairs"])
            self.assertEqual(summary["repairs"]["module_001"]["status"], "PASS")
            draft = (output / "drafts" / "06-module-module_001.md").read_text(encoding="utf-8")
            self.assertIn("## Agent 覆盖率修复", draft)
            self.assertIn("api_404", draft)
            coverage = json.loads((output / "coverage-symbols.json").read_text(encoding="utf-8"))
            self.assertEqual(coverage["modules"]["module_001"]["status"], "PASS")
            state = (output / "STATE_REPORT.md").read_text(encoding="utf-8")
            self.assertIn("failed_modules: []", state)
            acceptance = subprocess.run([str(output / "acceptance" / "check.sh")], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertEqual(acceptance.returncode, 0, acceptance.stdout + acceptance.stderr)

    def test_batch_agent_missing_module_block_fails_acceptance(self):
        broken = self.fake_tools / "broken-agent"
        broken.write_text(
            """#!/usr/bin/env python3
import sys
prompt = sys.stdin.read()
if "独立审稿 agent" in prompt:
    print("## Agent Cross-ref 审稿\\n\\n- 未发现跨模块矛盾。")
else:
    print("## Agent 深度分析\\n\\n- 没有按 MODULE_RESULT marker 输出。")
""",
            encoding="utf-8",
        )
        broken.chmod(0o755)

        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text("# Demo Tool\n", encoding="utf-8")
            (repo / "main.py").write_text("def run():\n    return 'ok'\n", encoding="utf-8")
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

            result = subprocess.run(
                [
                    sys.executable,
                    str(CLI),
                    str(repo),
                    "--output",
                    str(output),
                    "--no-question",
                    "--agent-mode",
                    "command",
                    "--agent-command",
                    "broken-agent",
                ],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            summary = json.loads((output / "AGENT_SUMMARY.json").read_text(encoding="utf-8"))
            self.assertEqual(summary["modules"]["module_001"]["status"], "FAIL")
            self.assertEqual(summary["status"], "FAIL")
            acceptance = subprocess.run([str(output / "acceptance" / "check.sh")], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertNotEqual(acceptance.returncode, 0, acceptance.stdout + acceptance.stderr)
            self.assertIn("agent summary pass", acceptance.stdout)

    def test_cross_ref_review_explicit_none_does_not_trigger_fallback_repair(self):
        review = """## Agent Cross-ref 审稿

- 重复定义未发现。
- module_001 当前没有跨模块冲突。
- 如果出现重复章节才需要回退 module_001。

建议回退模块: 无
"""

        self.assertEqual(repo_analyzer.cross_ref_repair_modules(review, ["module_001"]), [])

    def test_cross_ref_review_triggers_module_repair_and_rerun(self):
        repair_agent = self.fake_tools / "cross-ref-agent"
        repair_agent.write_text(
            """#!/usr/bin/env python3
import sys
from pathlib import Path

prompt = sys.stdin.read()
counter = Path(__file__).with_name("cross-ref-count.txt")

if "独立审稿 agent" in prompt:
    count = int(counter.read_text(encoding="utf-8")) if counter.exists() else 0
    counter.write_text(str(count + 1), encoding="utf-8")
    if count == 0:
        print("## Agent Cross-ref 审稿\\n\\n- 发现 module_001 职责边界不一致。\\n- 建议回退模块: module_001")
    else:
        print("## Agent Cross-ref 审稿\\n\\n- 未发现跨模块矛盾。\\n- 建议回退模块: 无")
elif "Cross-ref 修复" in prompt:
    print("## Agent Cross-ref 修复\\n\\n- 已补齐 module_001 的职责边界，避免和其他模块冲突。")
else:
    print("<!-- MODULE_RESULT: module_001 -->")
    print("## Agent 深度分析\\n\\n- 业务角色: 该模块承载主要执行路径。")
    print("<!-- END_MODULE_RESULT -->")
""",
            encoding="utf-8",
        )
        repair_agent.chmod(0o755)

        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"

            (repo / "README.md").write_text("# Demo Tool\n", encoding="utf-8")
            (repo / "main.py").write_text("def run():\n    return 'ok'\n", encoding="utf-8")
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

            result = subprocess.run(
                [
                    sys.executable,
                    str(CLI),
                    str(repo),
                    "--output",
                    str(output),
                    "--no-question",
                    "--agent-mode",
                    "command",
                    "--agent-command",
                    "cross-ref-agent",
                ],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            summary = json.loads((output / "AGENT_SUMMARY.json").read_text(encoding="utf-8"))
            self.assertEqual(summary["cross_ref_repairs"]["module_001"]["status"], "PASS")
            self.assertEqual(summary["cross_ref"]["status"], "PASS")
            self.assertEqual(summary["status"], "PASS")
            draft = (output / "drafts" / "06-module-module_001.md").read_text(encoding="utf-8")
            self.assertIn("## Agent Cross-ref 修复", draft)
            self.assertTrue((output / "agent-runs" / "cross-ref-repair-module_001" / "result.md").exists())
            self.assertTrue((output / "agent-runs" / "cross-ref-review-final" / "result.md").exists())
            review = (output / "drafts" / "07-cross-ref-agent-review.md").read_text(encoding="utf-8")
            self.assertIn("建议回退模块: 无", review)
            acceptance = subprocess.run([str(output / "acceptance" / "check.sh")], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertEqual(acceptance.returncode, 0, acceptance.stdout + acceptance.stderr)

    def test_config_sla_and_resume_are_recorded(self):
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"
            config = Path(out_tmp) / "repo-analyzer.json"

            (repo / "README.md").write_text("# Demo Tool\n", encoding="utf-8")
            (repo / "main.py").write_text("def run():\n    return 'ok'\n", encoding="utf-8")
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            output.mkdir()
            (output / "manual-note.md").write_text("keep me\n", encoding="utf-8")
            config.write_text(
                json.dumps(
                    {
                        "mode": "all",
                        "no_question": True,
                        "target_coverage_core": 0.8,
                        "target_coverage_minor": 0.2,
                        "coverage_engine": "regex",
                        "sla_minutes": 30,
                    }
                ),
                encoding="utf-8",
            )

            result = subprocess.run(
                [sys.executable, str(CLI), str(repo), "--output", str(output), "--config", str(config), "--resume"],
                cwd=ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertTrue((output / "manual-note.md").exists())
            effective = json.loads((output / "CONFIG_EFFECTIVE.json").read_text(encoding="utf-8"))
            self.assertEqual(effective["mode"], "all")
            self.assertTrue(effective["no_question"])
            self.assertEqual(effective["coverage_engine"], "regex")
            self.assertEqual(effective["agent_mode"], "deterministic")
            self.assertEqual(effective["agent_max_attempts"], 3)
            sla = (output / "SLA_REPORT.md").read_text(encoding="utf-8")
            self.assertIn("resumed: true", sla)
            self.assertIn("status: PASS", sla)
            self.assertTrue((output / "ANALYSIS_REPORT.business.md").exists())
            acceptance = subprocess.run([str(output / "acceptance" / "check.sh")], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.assertEqual(acceptance.returncode, 0, acceptance.stdout + acceptance.stderr)

    def test_defaults_extends_env_and_last_session_preferences(self):
        with tempfile.TemporaryDirectory() as repo_tmp, tempfile.TemporaryDirectory() as out_tmp:
            repo = Path(repo_tmp)
            output = Path(out_tmp) / "analysis"
            config_home = Path(out_tmp) / "config-home"
            config_home.mkdir()
            team = config_home / "team.yaml"
            defaults = config_home / "defaults.yaml"

            (repo / "README.md").write_text("# Demo Tool\n", encoding="utf-8")
            (repo / "main.py").write_text("def run():\n    return 'ok'\n", encoding="utf-8")
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

            team.write_text("mode: business\nsla_budget:\n  minutes: 12\ntarget_coverage:\n  core: 0.7\n", encoding="utf-8")
            defaults.write_text(f"extends:\n  - {team}\ncoverage_engine: regex\ntarget_coverage:\n  minor: 0.3\n", encoding="utf-8")
            env = {
                **os.environ,
                "REPO_ANALYZER_CONFIG_HOME": str(config_home),
                "REPO_ANALYZER_SLA_BUDGET_MINUTES": "22",
            }

            result = subprocess.run(
                [sys.executable, str(CLI), str(repo), "--output", str(output), "--no-question", "--save-pref"],
                cwd=ROOT,
                env=env,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            effective = json.loads((output / "CONFIG_EFFECTIVE.json").read_text(encoding="utf-8"))
            self.assertEqual(effective["mode"], "business")
            self.assertEqual(effective["coverage_engine"], "regex")
            self.assertEqual(effective["target_coverage_core"], 0.7)
            self.assertEqual(effective["target_coverage_minor"], 0.3)
            self.assertEqual(effective["sla_minutes"], 22.0)
            last_session = json.loads((config_home / "last-session.json").read_text(encoding="utf-8"))
            self.assertEqual(last_session["flags_used"]["mode"], "business")

            defaults.unlink()
            second = Path(out_tmp) / "analysis-2"
            env.pop("REPO_ANALYZER_SLA_BUDGET_MINUTES")
            rerun = subprocess.run(
                [sys.executable, str(CLI), str(repo), "--output", str(second), "--use-last-pref"],
                cwd=ROOT,
                env=env,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self.assertEqual(rerun.returncode, 0, rerun.stderr)
            second_effective = json.loads((second / "CONFIG_EFFECTIVE.json").read_text(encoding="utf-8"))
            self.assertEqual(second_effective["mode"], "business")
            self.assertEqual(second_effective["coverage_engine"], "regex")
